:index-group: Unrevised
:jbake-type: page
:jbake-status: status=published
= Configurando JSON-B

Este exemplo mostra como personalizar jsonb para uma aplicação JAX-RS.
JSONB é o novo padrão `jakartaee-api: 8.0` para serialização/desserialização de json.
Poucas anotações são necessárias e o `JsonbConfig` oferece muitas configurações.

== Executando e testando o Endpoint

A aplicação pode ser executada com `mvn clean install tomee: run` e se a porta 8080 estiver disponível, pode invocar o seguinte endpoint:

[source,bash]
----
$ curl -X GET http://localhost:8080/mp-jsonb-configuration/api/users
----

que deve responder com o seguinte json:

[source,bash]
----
[
  {
    "Id":1,
    "Name":"user 1",
    "Registration":"2018 - 12 - 28"
  },
  {
    "Id":2,
    "Name":"user 2",
    "Registration":"2018 - 12 - 28"
  }
]
----

== @ApplicationPath

A classe de ponto de partida JAX-RS

A classe de ponto de entrada JAXRS, da seguinte forma, os jaxrs carregarão todas as classes e métodos anotados com `@Path` sem especificá-los.

[source,java]
----
import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.core.Application;

@ApplicationPath("api")
public class JAXRSApplication extends Application {

}
----

== @Path Recurso Rest

Classe jaxrs simples com um método GET

[source,java]
----
import java.util.ArrayList;
import java.util.List;

import jakarta.ejb.Stateless;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

import org.superbiz.model.User;

@Path("users")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Stateless
public class UserService {

    @GET
    public List<User> users() {
        List<User> users = new ArrayList<>();
        User user1 = new User(1, "user 1");
        User user2 = new User(2, "user 2");
        users.add(user1);
        users.add(user2);

        return users;
    }
}
----

== Configurando JSONB

A implementação de `ContextResolver<>` pode personalizar os padrões de jaxrs; neste exemplo, vamos personalizar a serialização/desserialização JSONB

[source,java]
----
import jakarta.json.bind.Jsonb;
import jakarta.json.bind.JsonbBuilder;
import jakarta.json.bind.JsonbConfig;
import jakarta.json.bind.config.PropertyNamingStrategy;
import jakarta.ws.rs.ext.ContextResolver;
import jakarta.ws.rs.ext.Provider;

@Provider
public class JSONBConfiguration implements ContextResolver<Jsonb> {

    private Jsonb jsonb;

    public JSONBConfiguration() {
        // jsonbConfig offers a lot of configurations.
        JsonbConfig config = new JsonbConfig().withFormatting(true)
                .withPropertyNamingStrategy(PropertyNamingStrategy.UPPER_CAMEL_CASE)
                .withDateFormat("yyyy - MM - dd", Locale.ENGLISH);

        jsonb = JsonbBuilder.create(config);
    }

    @Override
    public Jsonb getContext(Class<?> type) {
        return jsonb;
    }

}
----

`JsonbConfig` oferece muitas configurações.

== Acessando o Recurso Rest

O teste implanta o aplicativo da web no TomEE embedded com o Arquillian e invoca o endpoint `/users`

[source,java]
----
package org.superbiz.rest;

import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.apache.cxf.jaxrs.client.WebClient;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.arquillian.test.api.ArquillianResource;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.superbiz.JAXRSApplication;
import org.superbiz.JSONBConfiguration;
import org.superbiz.model.User;

@RunWith(Arquillian.class)
public class UserServiceTest {

	@ArquillianResource
	private URL base;

	@Deployment(testable = false)
	public static WebArchive app() {
		return ShrinkWrap.create(WebArchive.class)
				.addClasses(UserService.class, JAXRSApplication.class, JSONBConfiguration.class, User.class);
	}

	@Test
	public void get() throws IOException {
		final String message = WebClient.create(base.toExternalForm()).path("api/users").get(String.class);
		System.out.println(message);

		final SimpleDateFormat sdf = new SimpleDateFormat("yyyy - MM - dd");

		// test withDateFormat("yyyy - MM - dd")
		Assert.assertTrue(message.contains(sdf.format(new Date())));
		// test withFormatting(true)
		Assert.assertTrue(message.contains(System.getProperty("line.separator")));
	}

}
----

== Executando
A execução do exemplo pode ser feita a partir do maven com um simples comando `mvn clean install`, executando no diretorio `mp-jsonb-configuration`.

Quando executado, você deve ver uma saída semelhante à seguinte:

[source,console]
----
Running org.superbiz.rest.UserServiceTest
INFO: Starting TomEE from: /tmp/arquillian-apache-tomee-24910
INFO: Starting Servlet engine: [Apache Tomcat/11.0.25]
INFO: Starting ProtocolHandler ["http-nio-53035"]
INFO: Configuring enterprise application: /path/to/tomee/examples/mp-jsonb-configuration/target/tomee-embedded/0/4835cda6-1e53-4232-ad75-25e7dd844887
INFO: Enterprise application "/path/to/tomee/examples/mp-jsonb-configuration/target/tomee-embedded/0/4835cda6-1e53-4232-ad75-25e7dd844887" loaded.
INFO: Deployed Application(path=/path/to/tomee/examples/mp-jsonb-configuration/target/tomee-embedded/0/4835cda6-1e53-4232-ad75-25e7dd844887)
INFO: Provider{clazz=org.superbiz.JSONBConfiguration, discovered=true, singleton=false}
INFO: REST Application: http://localhost:53035/4835cda6-1e53-4232-ad75-25e7dd844887/api       -> org.superbiz.JAXRSApplication
INFO:      Service URI: http://localhost:53035/4835cda6-1e53-4232-ad75-25e7dd844887/api/users ->  EJB org.superbiz.rest.UserService
INFO:               GET http://localhost:53035/4835cda6-1e53-4232-ad75-25e7dd844887/api/users ->      List<User> users()
[
  {
    "Id":1,
    "Name":"user 1",
    "Registration":"2026 - 09 - 22"
  },
  {
    "Id":2,
    "Name":"user 2",
    "Registration":"2026 - 09 - 22"
  }
]
INFO: Undeploying app: /path/to/tomee/examples/mp-jsonb-configuration/target/tomee-embedded/0/4835cda6-1e53-4232-ad75-25e7dd844887
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.056 s -- in org.superbiz.rest.UserServiceTest
Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

=== Dentro do jar

`jakartaee-api: 8.0` ele incorpora todas as dependências necessárias para ativar um aplicativo REST em funcionamento.

Se olharmos para o jar construído pelo maven, veremos que o aplicativo em si é bem pequeno:

[source,bash]
----
$ jar tvf target/mp-jsonb-configuration-10.0.0-M1-SNAPSHOT.war
     0 Fri Dec 28 19:36:10 CET 2018 META-INF/
   134 Fri Dec 28 19:36:08 CET 2018 META-INF/MANIFEST.MF
     0 Fri Dec 28 19:36:08 CET 2018 WEB-INF/
     0 Fri Dec 28 19:36:08 CET 2018 WEB-INF/classes/
     0 Fri Dec 28 19:36:08 CET 2018 WEB-INF/classes/org/
     0 Fri Dec 28 19:36:08 CET 2018 WEB-INF/classes/org/superbiz/
     0 Fri Dec 28 19:36:08 CET 2018 WEB-INF/classes/org/superbiz/model/
     0 Fri Dec 28 19:36:08 CET 2018 WEB-INF/classes/org/superbiz/rest/
  1165 Fri Dec 28 19:36:06 CET 2018 WEB-INF/classes/org/superbiz/model/User.class
   402 Fri Dec 28 19:36:06 CET 2018 WEB-INF/classes/org/superbiz/JAXRSApplication.class
  1194 Fri Dec 28 19:36:06 CET 2018 WEB-INF/classes/org/superbiz/rest/UserService.class
  1701 Fri Dec 28 19:36:06 CET 2018 WEB-INF/classes/org/superbiz/JSONBConfiguration.class
  1224 Fri Dec 28 18:28:32 CET 2018 WEB-INF/web.xml
     0 Fri Dec 28 19:36:10 CET 2018 META-INF/maven/
     0 Fri Dec 28 19:36:10 CET 2018 META-INF/maven/org.superbiz/
     0 Fri Dec 28 19:36:10 CET 2018 META-INF/maven/org.superbiz/mp-jsonb-configuration/
  1791 Fri Dec 28 19:10:44 CET 2018 META-INF/maven/org.superbiz/mp-jsonb-configuration/pom.xml
   128 Fri Dec 28 19:36:08 CET 2018 META-INF/maven/org.superbiz/mp-jsonb-configuration/pom.properties
----

Esse jar individual pode ser implantado em qualquer implementação Java EE que atenda aos requisitos. No TomEE, basta colocá-lo no diretório `${tomee.home}/webapps/`.
