:index-group: REST
:jbake-type: page
:jbake-status: status=published

= REST Simples

Definir um serviço REST é fácil, simplesmente adicione a anotação ``@Path`` na classe, então defina o método HTTP (``@GET``, ``@POST``, ...) ao método da classe que deseja usar.

= O código

== O Serviço REST: ``@Path``, ``@GET``, ``@POST``

Aqui nós temos um REST simples, anotamos a classe com ``@Path("/greeting")`` para indicar a rota correspondente a classe ``GreetingService``. Definimos ``message()`` como ``@GET`` e ``lowerCase()`` como ``@POST`` para esta rota ``/greeting``. Pronto, temos um serviço! Simples não?

[source,java]
----
package org.superbiz.rest;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;

@Path("/greeting")
public class GreetingService {
    @GET
    public String message() {
        return "Hi REST!";
    }

    @POST
    public String lowerCase(final String message) {
        return "Hi REST!".toLowerCase();
    }
}
----

== Testando

=== Teste para o serviço JAXRS

Usamos o Arquillian com o adaptador TomEE embedded, assim o serviço REST roda em um TomEE real.

O método ``@Deployment`` cria a aplicação web a ser implantada. Aqui ela contém apenas a classe ``GreetingService``, mas você também pode adicionar sua aplicação REST e um ``web.xml``. ``testable = false`` executa os métodos de teste como cliente da aplicação implantada, e ``@ArquillianResource`` injeta a URL base dela.

Finalmente para testar nós usamos o client API do ``cfx`` para chamar o serviço REST nos métodos ``get()`` e ``post()``.

O contêiner é configurado em ``src/test/resources/arquillian.xml``: ``httpPort`` com valor ``-1`` inicia o TomEE em uma porta aleatória.

[source,java]
----
package org.superbiz.rest;

import org.apache.cxf.jaxrs.client.WebClient;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.arquillian.test.api.ArquillianResource;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.IOException;
import java.net.URL;

import static org.junit.Assert.assertEquals;

@RunWith(Arquillian.class)
public class GreetingServiceTest {

    @ArquillianResource
    private URL base;

    @Deployment(testable = false)
    public static WebArchive app() {
        return ShrinkWrap.create(WebArchive.class).addClass(GreetingService.class);
    }

    @Test
    public void get() throws IOException {
        final String message = WebClient.create(base.toExternalForm()).path("greeting/").get(String.class);
        assertEquals("Hi REST!", message);
    }

    @Test
    public void post() throws IOException {
        final String message = WebClient.create(base.toExternalForm()).path("greeting/").post("Hi REST!", String.class);
        assertEquals("hi rest!", message);
    }
}
----

= Running

Executar o exemplo é bastante simples. No diretório ``simple-rest`` dê o seguinte comando:
[source,java]
----
$ mvn clean install
----
Com isso, provavelmente você terá a seguinte saida.
[source,java]
----
Running org.superbiz.rest.GreetingServiceTest
INFO: Starting TomEE from: /tmp/arquillian-apache-tomee-20908
INFO: Starting Servlet engine: [Apache Tomcat/11.0.25]
INFO: Starting ProtocolHandler ["http-nio-52756"]
INFO: Configuring enterprise application: /path/to/tomee/examples/simple-rest/target/tomee-embedded/0/5cfb3d73-fabd-4bc4-8550-88f254fe1095
INFO: Enterprise application "/path/to/tomee/examples/simple-rest/target/tomee-embedded/0/5cfb3d73-fabd-4bc4-8550-88f254fe1095" loaded.
INFO: Deployed Application(path=/path/to/tomee/examples/simple-rest/target/tomee-embedded/0/5cfb3d73-fabd-4bc4-8550-88f254fe1095)
INFO: REST Application: http://localhost:52756/5cfb3d73-fabd-4bc4-8550-88f254fe1095/         -> org.apache.openejb.server.rest.InternalApplication
INFO:      Service URI: http://localhost:52756/5cfb3d73-fabd-4bc4-8550-88f254fe1095/greeting -> Pojo org.superbiz.rest.GreetingService
INFO:               GET http://localhost:52756/5cfb3d73-fabd-4bc4-8550-88f254fe1095/greeting ->      String message()
INFO:              POST http://localhost:52756/5cfb3d73-fabd-4bc4-8550-88f254fe1095/greeting ->      String lowerCase(String)
INFO: Undeploying app: /path/to/tomee/examples/simple-rest/target/tomee-embedded/0/5cfb3d73-fabd-4bc4-8550-88f254fe1095
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.613 s -- in org.superbiz.rest.GreetingServiceTest
Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----
