#!/bin/sh
#============================================================
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#============================================================
#   Control script for OpenEJB
#   --------------------------
#    
#   This script is the central entry point to 
#   all of OpenEJB's functions.
#  
#   Contributed by:
#
#    - David Blevins <david.blevins@visi.com>
#    - Daniel S. Haischt <daniel.haischt@daniel-s-haischt.biz>
#             
#               
# ___________________________________________________________
# $Rev$ $Date$
#============================================================

cygwin=false
case "`uname`" in
CYGWIN*) cygwin=true;;
esac

if [ -z "$OPENEJB_HOME" -o ! -d "$OPENEJB_HOME" ] ; then
  # find OpenEJB
  if [ -d /opt/openejb ] ; then
    OPENEJB_HOME=/opt/openejb
  fi

  if [ -d "${HOME}/opt/openejb" ] ; then
    OPENEJB_HOME="${HOME}/opt/openejb"
  fi

  ## resolve links - $0 may be a link to openejb's home
  PRG="$0"
  progname=`basename "$0"`

  # need this for relative symlinks
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
    else
      PRG=`dirname "$PRG"`"/$link"
    fi
  done


  OPENEJB_HOME=`dirname "$PRG"`/..

  # make it fully qualified
  OPENEJB_HOME=`cd "$OPENEJB_HOME" && pwd`
fi

if $cygwin; then
  OPENEJB_HOME=`cygpath --path --windows "$OPENEJB_HOME"`
fi

echo OPENEJB_HOME = $OPENEJB_HOME

OPTIONS="-Dopenejb.home=$OPENEJB_HOME"

OPENEJB_CORE_JAR="$OPENEJB_HOME/lib/openejb-core-${pom.version}.jar"

#============================================================
_command_help()
{
    case $2 in
        "validate")
            java -jar $OPENEJB_CORE_JAR validate --help
        ;;
        "deploy")
            java -jar $OPENEJB_CORE_JAR deploy --help
        ;;
        "start")
            java -jar $OPENEJB_CORE_JAR start --help
        ;;
        "stop")
            java -jar $OPENEJB_CORE_JAR stop --help
        ;;
        "test")
            java -jar $OPENEJB_CORE_JAR test --help
        ;;
        *)
            java -jar $OPENEJB_CORE_JAR
        ;;
    esac
}
#============================================================
_command_deploy()
{
   shift
   java -jar $OPENEJB_CORE_JAR deploy $@
}
#============================================================
_command_validate()
{
   shift
   java -jar $OPENEJB_CORE_JAR validate $@
}
#============================================================
_command_start()
{
   java -jar $OPENEJB_CORE_JAR start $@
}
#============================================================
_command_stop()
{
   java -jar $OPENEJB_CORE_JAR stop $@
}
#============================================================
_test_intravm()
{
   java -jar $OPENEJB_CORE_JAR test local
}
#============================================================
_test_server()
{
   java -jar $OPENEJB_CORE_JAR test remote
}
#============================================================
_command_test()
{
case $2 in
    "local")
        _test_intravm
    ;;
    "remote")
        _test_server
    ;;
    "--help")
        _test_help
    ;;
    *)
        _test_noargs
    ;;
esac
}
#============================================================
_test_help()
{
   java -jar $OPENEJB_CORE_JAR test --help
}
#============================================================
_test_noargs()
{
   _test_intravm
   _test_server
}
#============================================================
case $1 in
    "build")
        _command_build $@
    ;;
    "test")
        _command_test $@
    ;;
    "validate")
        _command_validate $@
    ;;
    "deploy")
        _command_deploy $@
    ;;
    "start")
        _command_start $@
    ;;
    "stop")
        _command_stop $@
    ;;
    "corba")
        _start_corba $@
    ;;
    "create_stubs")
        _create_stubs $@
    ;;
    "help")
        _command_help $@
    ;;
    "-help")
        _command_help $@
    ;;
    "--help")
        _command_help $@
    ;;
    *)  _command_help $@
    ;;
esac



