
= TomEE deployment on Azure

This example uses a basic echo application, deployed with embedded TomEE on the Azure Cloud.

We use the TomEE maven plugin to package the app with TomEE Embedded
in order to generate a fat jar. This jar is then picked up and deployed by the azure-webapp-maven-plugin.

== Azure Setup

In order for the Azure plugin to work, you will need to have an Azure account and add a subscription to it.
Then, on yor development machine, install the Azure command-line interface (CLI) and authenticate with the command
line, before you can deploy your application.

- Create an Azure Account, if you don't have one, at https://azure.microsoft.com/en-us
- Use the free option, if available or https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade[add a subscription].
- https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest[Install] the Azure (CLI) according
to operating system of the computer you are using to develop.

- Finally you can setup your development computer.

=== Login into Azure

`az login`

The result:

----
[
   {
     "cloudName": "AzureCloud",
     "id": "aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaa",
     "isDefault": true,
     "name": "Pay-As-You-Go",
     "state": "Enabled",
     "tenantId": "bbbbbbb-bbbbb-bbbb-bbbbb-bbbbbbbbbbb",
     "user": {
       "name": "<your azure account's email>",
       "type": "user"
     }
   }
 ]
----
The TenantId is someone that can register and manage apps, yourself. You will need that for later.


=== Create a service principal
An Azure service principal is a security identity used by user-created apps, services,
and automation tools to access specific Azure resources:

`az ad sp create-for-rbac --name ServicePrincipalName --password <Choose a strong password>`

----
az ad sp create-for-rbac --name http://cloud-azure2 --password <password for this app>

{
  "appId": "cccccccc-cccc-cccc-cccc-ccccccccccccccc",
  "displayName": "cloud-azure2",
  "name": "http://cloud-azure2",
  "password": "<password for this app>",
  "tenant": "bbbbbbb-bbbbb-bbbb-bbbbb-bbbbbbbbbbb"
}
----
The ServicePrincipalName will also be set as subdomain name. In this case "http://cloud-azure2".
The appId is the identification of the app service.

=== Configure Maven

We now need to setup Maven's settings.xml so the azure-webapp-maven-plugin can authenticate against Azure:

On `~/.m2/settings.xml` please add a new server:
----
<server>
  <id>azure-auth</id>
  <configuration>
     <client>cccccccc-cccc-cccc-cccc-ccccccccccccccc</client>
     <tenant>bbbbbbb-bbbbb-bbbb-bbbbb-bbbbbbbbbbb</tenant>
     <key><password for this app></key>
     <environment>AZURE</environment>
   </configuration>
</server>
----
That's it you can now build the example and deploy it to Azure just using Maven:

`mvn clean install azure-webapp:deploy`



==== Notes

To deploy the echo app locally you can execute:

`mvn tomee:run`

You can test the app by calling `http://localhost:8080/cloud-azure-8.0.0-SNAPSHOT/echo/blabla`

It will return blabla

