//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.08 at 06:01:06 PM PDT 
//


package org.openejb.jee2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * 	The transaction-typeType specifies an enterprise bean's
 * 	transaction management type.
 * 
 * 	The transaction-type must be one of the two following:
 * 
 * 	    Bean
 * 	    Container
 */
public enum TransactionTypeType {
    @XmlEnumValue("Bean") BEAN,
    @XmlEnumValue("Container") CONTAINER;
}
