= Java EE 7 Implementation Status
:index-group: Unrevised
:jbake-date: 2018-12-05
:jbake-type: page
:jbake-status: published


This page shows the current implementation status for the Java EE 7
specification compabitility of Apache Tomme 7.0.0-M1. Currently, we are
working on the certification for Java EE 7.

Version

JSR

TomEE

TomEE+

Java Servlets

3.1

340

(/)

(/)

JavaServer Pages (JSP)

2.3

245

(/)

(/)

Expression Language (EL)

3.0

341

(/)

(/)

JavaServer Faces (JSF)

2.2

344

(/)

(/)

Java API for Websocket

1.0

356

(/)

(/)

Java API for JSON Processing (JSON-P)

1.0

353

(/)

(/)

Batch Applications for the Java Platform

1.0

352

(/)

Concurrency Utilities for Java EE

1.0

236

(/)

Contexts and Dependency Injection (CDI)

1.1

346

(/)

(/)

Bean Validation

1.1

349

(/)

(/)

Enterprise JavaBeans (EJB)

3.2

345

(/)

(/)

Interceptors

1.2

318

(/)

(/)

Java EE Connector Architecture

1.6

322

1.7 not supported yet

Java Persistence API (JPA)

2.1

338

API 2.1 supported, default provider still 2.0.

API 2.1 supported, default provider still 2.0.

Java Messaging Service (JMS)

1.1

343

2.0 not supported yet.

Java Transaction API (JTA)

1.2

907

(/)

(/)

JavaMail API

1.5

919

(/)

(/)

Java API for RESTful Web Services (JAX-RS)

2.0

339

(/)

(/)

Java API for XML Web Services (JAX-WS)

2.2

224

(/)

Java Authentication Service Provider Interface for Containers (JAAS)

1.1

196

(/)

(/)

Java Authorization Contract for Coners (JACC)

1.5

115

(/)

(/)
