:index-group: Unrevised
:jbake-date: 2018-12-05
:jbake-type: page
:jbake-status: published


= Maven
Information

This page is intended to provide an insight into basic
https://maven.apache.org/[Maven] usage for users that are not all that
familiar with https://maven.apache.org/[Maven] projects. It is by no
means a tutorial and is designed to be more of a _quickstart_ to get you
up and running.

You can find a really good https://maven.apache.org/[Maven] tutorial
here: the Sonatype "Maven by Example" book.

It is assumed that:

* You have downloaded and installed https://maven.apache.org/[Maven] and
that you can run *mvn --version* from any command prompt (or console).
* You have downloaded and installed
https://subversion.apache.org/[Subversion] and that you can run *svn
--version* from any command prompt or console.

It is also assumed you have downloaded one of the following:

* One of the example projects from
https://github.com/apache/tomee/tree/main/examples
* The entire project source from
https://github.com/apache/tomee

Use https://git-scm.com/[Git] to check out the example
sources from a console like so:

[source,bash]
----
git clone https://github.com/apache/tomee.git

----

Or that you may of course also be using your own project pom.xml

If you want to use the latest snapshot locate the __ section in your
pom.xml and ensure the following repository exists:

[source,xml]
----
<repositories>
  <repository>
    <id>apache-m2-snapshot</id>
    <name>Apache M2 Snapshot Repository</name>
    <url>https://repository.apache.org/snapshots/</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
----
