:index-group: Unrevised
:jbake-date: 2018-12-05
:jbake-type: page
:jbake-status: published


= Maven
Information

This page is intended to provide an insight into basic
http://maven.apache.org/[Maven] usage for users that are not all that
familiar with http://maven.apache.org/[Maven] projects. It is by no
means a tutorial and is designed to be more of a _quickstart_ to get you
up and running.

You can find a really good http://maven.apache.org/[Maven] tutorial
here: http://books.sonatype.com/mvnex-book/reference/public-book.html

It is assumed that:

* You have downloaded and installed http://maven.apache.org/[Maven] and
that you can run *mvn --version* from any command prompt (or console).
* You have downloaded and installed
http://subversion.apache.org/[Subversion] and that you can run *svn
--version* from any command prompt or console.

It is also assumed you have downloaded one of the following:

* One of the example projects from
link:[http://svn.apache.org/repos/asf/tomee/tomee/trunk/examples]
* The entire project source from
http://svn.apache.org/repos/asf/tomee/tomee/trunk

Use http://subversion.apache.org/[Subversion] to checkout the example
sources from a console like so:

[source,bash]
----
svn co http://svn.apache.org/repos/asf/tomee/tomee/trunk/examples/[example]
    
----

Or that you may of course also be using your own project pom.xml

If you want to use the latest snapshot locate the __ section in your
pom.xml and ensure the following repository exists:

[source,xml]
----
<repositories>
  <repository>
    <id>apache-m2-snapshot</id>
    <name>Apache M2 Snapshot Repository</name>
    <url>http://repository.apache.org/snapshots/</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
----
