= Quickstart
:index-group: OpenEJB Standalone Server
:jbake-date: 2018-12-05
:jbake-type: page
:jbake-status: published

= Installation

To install OpenEJB, simply link:downloads.html[download the latest
binary] and unpack your zip or tar.gz into the directory where you want
OpenEJB to live.

Windows users can download the zip and unpack it with the WinZip
program.

Linux users can download the tar.gz and unpack it with the following
command:

_tar xzvf openejb-3.0.tar.gz_

Congratulations, you've installed OpenEJB.

If you've unpacked OpenEJB into the directory C:-3.0, for example, then
this directory is your OPENEJB_HOME directory. The OPENEJB_HOME
directory is referred to in various parts of the documentation, so it's
good to remember where it is.

= Using OpenEJB

Now all you need to do is move to the bin directory in OPENEJB_HOME, the
directory where OpenEJB was unpacked, and type:

_openejb_

For Windows users, that looks like this:

*C:-3.0> bin

For UNIX/Linux/Mac OS X users, that looks like this:

`[user@host openejb-3.0](user@host-openejb-3.0.html) # ./bin/openejb`

You really only need to know two commands to use OpenEJB,
openejbx30:deploy-tool.html[deploy] and [start|OPENEJBx30:Startup] .
Both are completely documented and have examples.

For help information and command options, try this:

__________________________________________
openejb deploy --help openejb start --help
__________________________________________

For examples on using the start command and options, try this:

________________________
openejb start --examples
________________________

That's it!

If you don't have any EJBs or clients to run, try the ubiquitous
openejbx30:hello-world.html[Hello World] example.

= Join the mailing list

The OpenEJB User list is where the general OpenEJB community goes to ask
questions, make suggestions, chat with other users, and keep a finger on
the pulse of the project. More information about the user list and dev
list can be found link:mailing-lists.html[here]
