= Running a standalone OpenEJB server
:index-group: EJB
:jbake-date: 2018-12-05
:jbake-type: page
:jbake-status: published


= Configuring the OpenEJB Runtime

The OpenEJB Eclipse plugin provides support for running OpenEJB as a standalone server in Eclipse using WTP.

To set up a server, first of all, you will need to have a copy of OpenEJB
extracted on your machine. Once you have that, the next step is to set
up a runtime.

To set up a new runtime, click on Window, Preferences, and select
Installed Runtimes under the Server category. Click the Add button.

Select OpenEJB 3.0.0 from the Apache category, and click next. If you
choose to 'also create a new server' on this panel, you can add a server
straight after configuring the runtime.

Browse to, or enter the path to your copy of OpenEJB. Click on Finish.

= Configuring the OpenEJB Server Open the Servers view (if it isn't
already), and right click and select New->Server.

Select OpenEJB 3.0.0 from the Apache category, ensure you have the
OpenEJB runtime selected, and click Next.

Select the EJB port for the server, and select Finish.

= Deploying a project In order to deploy your project to an OpenEJB
server in Eclipse, your project must be a Java EE project, with the EJB
facet enabled. If your project doesn't have the Faceted nature, you can
use the OpenEJB plugin to add it. Simply select OpenEJB->Add Faceted
Nature from the menu bar.

To add the EJB facet, right-click on the project in the navigator, and
select Properties. Select Project Facets on the left hand side. Click on
the Modify Project button.

Select the EJB Module facet, and the Java Facet. Remember to select your
OpenEJB runtime too. Click Next.

Enter the source folder for the EJBs in your project and click Finish.

Now right-click on your OpenEJB server in the servers view, and select
Add and Remove Projects.

Add your project to the server, and click Finish.

To start the server, right-click on your OpenEJB server, and select
Start.
